server:
  port: 12300

spring:
  application:
    name: config-server
  profiles:
    active: jdbc
  cloud:
    config:
      name: config-server
      server:
        default-label: master
        jdbc:
          sql: select `key`, `value` from `config_info` where `application`=? and `profile`=? and `label`=?

# mysql 属性配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_config
    username: root
    password: root

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:12000/eureka #eureka服务端提供的注册地址 参考服务端配置的这个路径
  instance:
    instance-id: config-server-1 #实例名
    prefer-ip-address: true #是否显示IP地址
    leaseRenewalIntervalInSeconds: 10 #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
    leaseExpirationDurationInSeconds: 30 #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒

######  使用git  ######
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xiezhibing/test.git #配置文件在github上的地址
#          username: xxxx
#          password: xxxx
#          search-paths: config, dev* #Configserver会在 Git仓库根目录、 config子目录，以及所有以dev开始的子目录中查找配置文件。
#          clone-on-start: true #启动时就clone仓库到本地，默认是在配置被首次请求时，config server才会clone git仓库
#        native:
#          search-locations: classpath:/config #若配置中心在本地，本地的地址


management:
  endpoints:
    web:
      exposure:
        include: "*"
